services:
  portal-frontend:
    container_name: portal-frontend
    image: ghcr.io/nl-portal/portal-frontend:main-202503201143-d61d51ae@sha256:eef102d690cc64c54a91dad685774f60849c0e5b7587dbdd51c0d83aab282933
    restart: unless-stopped
    ports:
      - "3000:8080"
    platform: linux/amd64
    networks:
      - backend
    environment:
      KEYCLOAK_URL: "http://localhost:8080/auth"
      KEYCLOAK_REALM: "nlportal"
      KEYCLOAK_CLIENT_ID: "gzac-portal"
      KEYCLOAK_REDIRECT_URI: "http://localhost:3000"
      GRAPHQL_URI: "http://localhost:8085/graphql"
      REST_URI: "http://localhost:8085/api"
      SHOW_INHABITANT_AMOUNT: "true"
      ADDRESS_RESEARCH_URL: "http://some-address-research-url"

  portal-backend:
    container_name: portal-backend
    image: ghcr.io/nl-portal/portal-backend:main-202503191650-55a28895
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      - db
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nl-portal
      SPRING_DATASOURCE_NAME: nl-portal
      SPRING_DATASOURCE_USERNAME: nlportal
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/auth/realms/nlportal
    platform: linux/amd64
    networks:
      - backend

  db:
    image: postgres:15
    container_name: postgres_database
    environment:
        POSTGRES_DB: nl-portal
        POSTGRES_USER: nlportal
        POSTGRES_PASSWORD: password
    ports:
      - "15431:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak_server
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://portal-keycloak-database/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    depends_on:
      - portal-keycloak-database
    command: "start-dev --import-realm"
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./imports/keycloak:/opt/keycloak/data/import

  portal-keycloak-database:
    image: postgres:15
    container_name: portal-keycloak-database
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: